# Generated by Django 5.2 on 2025-04-23 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='name',
        ),
        migrations.AddField(
            model_name='tariff',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='tariff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='subscriptions.tariff', verbose_name='Тариф'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
